name: Fetch Air Quality Data

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    container:
      image: python:3.11-alpine  # Use Alpine-based Python image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        run: |
          apk add --no-cache bash git openssh
          python -m ensurepip
          python -m pip install --upgrade pip setuptools wheel

      - name: Set environment variables
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "ATLAS_URI=${{ secrets.ATLAS_URI }}" >> $GITHUB_ENV
          echo "MONGO_DB=${{ secrets.MONGO_DB }}" >> $GITHUB_ENV
          echo "MONGO_COLLECTION=${{ secrets.MONGO_COLLECTION }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run fetch.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MONGO_URI: ${{ secrets.ATLAS_URI }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          MONGO_COLLECTION: ${{ secrets.MONGO_COLLECTION }}
        run: python fetch.py
