name: Fetch Air Quality Data

on:
  push:
    branches:
      - main  # Run on push to main branch

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          MONGO_COLLECTION: ${{ secrets.MONGO_COLLECTION }}
        run: python fetch.py
